#!perl
use strict;
use warnings; 

use lib("./lib");
use ares_core;
use ares_game;
use ares_map;

use lib("../../lib/perl");
use Starmade::Message;
use Starmade::Player;
use Starmade::Base;
use Stard::Log;

ares_setup_run_env('.');

set_loglevel(6);


main(@ARGV);
exit 0;


##############################################

## main
sub main {
	my $player = $_[0];
	my $map = $_[1];

	if ($player && $player ne '' && !starmade_is_admin($player)) {
		starmade_broadcast("$player, You are not an admin, and cannot run that command.");
		stdout_log("$player, denied access to ares_start_game: Player is not an admin", 4);
		exit 1;
	}
	stdout_log("New game started by $player", 5);
	ares_set_game_state('complete');
	if ($map) {
		ares_start_new_game($map);
	}
	else {
		ares_start_new_game();
	}
}
