#!perl
use File::Basename;

use lib("./lib");
use lib("../../lib");
use ares_core;
use ares_vote;
use ares_map;
use stard_lib;
use stard_log;

$|=1;

## setup environment
ares_setup_run_env('.');
stard_setup_run_env("./../../");



main(@ARGV);
exit 0;
############################################

# real work starts where
sub main {
	my $player = $_[0];
	my $map = $_[1];

	my @maps = @{ares_get_map_list()};
	my $match = 0;
	foreach my $amap (@maps) {
		if ($map eq $amap) {
			$match = 1;
		}
	};

	
	if ($match) {
		ares_vote_for($player, $map);
		stard_broadcast("$player, your vote has been cast");
	}
	else {
		stard_pm($player, "The map you voted for doesn't exist!");
		usage($player);
	}
};


sub usage {
	my $player = $_[0];
	stard_pm($player, "stard_vote <map>");
	stard_pm($player, "desc: vote for the map you want to play next game. To see what maps are available type !ares_maps");
}
