#!perl
use File::Basename;

use lib("./lib");
use ares_core;
use ares_map;

use lib("../../lib/perl");
use Starmade::Message;
use Stard::Log;

$|=1;

## setup environment
starmade_setup_lib_env("./../../");



main(@ARGV);
exit 0;
############################################

# real work starts where
sub main {
	my $player = $_[0];

	my @maps = @{ares_get_map_list()};
	my $cur_map = ares_get_cur_map();

	if ($cur_map) {
		starmade_pm($player, "Current Map: $cur_map");
	}
	starmade_pm($player, "Available Maps:");
	foreach my $map (@maps) {
		starmade_pm($player, $map);
	};
};
