#!perl
use strict;
use File::Basename;

use lib("./lib");
use ares_core;
use ares_game;
use ares_player;

use lib("../../lib/perl");
use Starmade::Message;
use Stard::Log;

$|=1;


ares_setup_run_env('.');



main(@ARGV);
exit 0;
############################################################################

# real work starts where
sub main {
	my $player = $_[0];
	my $type = $_[1];

	if ($type && $type ne 'base' && $type ne 'control') {
		usage();
	}

	my $faction = ares_get_player_faction($player);	
	
	starmade_broadcast("Current game status has been sent to you, $player.");
	starmade_pm($player, ares_game_status_string($faction, $type));
};

sub usage {
	my $player = $_[0];

	starmade_pm($player, "Usage: !status <type>");
	starmade_pm($player, "Desc: Get the game, base and control point status");
	starmade_pm($player, "Valid types: base, control");
}
