#!perl
use strict;
use warnings;

my $ares_player_state = "./State/Players";

main(@ARGV);


exit 0;
##############################################



sub main {
	my $player = $_[0];
	exec("touch", "$ares_player_state/$player.dead");
}
