#!perl
use strict;
use warnings;

use lib("./lib");
use ares_core;
use ares_game;
use ares_faction;
use ares_player;
use lib("../../lib");
use stard_lib;
use stard_log;

ares_setup_run_env('.');
stard_setup_run_env("./../../");

main(@ARGV);

my $ares_player_state = "./State/Players"

exit 0;
##############################################




sub main {
	my $player = $_[0];
	exec("touch", "$ares_player_state/$player.dead");
}
